accessible: true
author: Pierre Ortegat
categories: []
contact_url: ''
context: |+
    .. container:: row

        .. container:: col-md-10 text-justify

            The foo is the real bar !

environment_id: default
environment_parameters:
    limits:
        memory: '100'
        time: '30'
        hard_time: ''
    run_cmd: ''
environment_type: docker
evaluate: best
file: ''
groups: false
input_random: '0'
name: 3. Combined fuzzer
network_grading: false
order: 5
problems:
    studentcode:
        language: ''
        default: ''
        name: Combined fuzzer
        type: code
        header: |-
            Yolooooo
stored_submissions: 0
submission_limit:
    amount: -1
    period: -1
weight: 1.0